kind: Service
apiVersion: v1
metadata:
  name: app-service-movement
spec:
  type: LoadBalancer
  selector:
    app: service-movement
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5005
    name: http
 